version: 0.2

phases:
  install:
    commands:
      - echo Bootstraping build dependencies...
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Sync /dist to $S3_BUCKET
      - aws s3 sync ./dist $S3_BUCKET